kind: pipeline
name: triton

steps:
  - name: Compile
    image: ubuntu:latest
    environment:
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    TELEGRAM_CHAT:
      from_secret: TELEGRAM_CHAT
    commands:
      - apt-get update && apt-get install -y bison build-essential bc bison curl libssl-dev git zip wget
      - chmod +x build.sh
      - bash build.sh
      